### ISSUE TITLE
Make the script scale for StackOverflow

### ISSUE THREAD

**Issue by amirouche** [openzim/sotoki#15]
SO is much bigger than SU. It's assumed that the data fits into RAM both during build and during browser e.g. the index page displays every single tag, this might not work on SO.
- [ ] Fix build
- [ ] Fix website

**Comment by kelson42** [comment]
I'll make a new run with SO xml files to see it this works.

**Comment by kelson42** [comment]
I have tried but the script crashs at the beginning, not sure this is related to the XML files

(venv)kelson@zimfarm:/srv/sotoki$ ls -la *xml
-rw-r--r-- 1 kelson kelson  2016042158 Mar  7 22:08 Badges.xml
-rw-r--r-- 1 kelson kelson 12166668726 Mar  7 22:15 Comments.xml
-rw-r--r-- 1 kelson kelson 71927132845 Mar  7 22:52 PostHistory.xml
-rw-r--r-- 1 kelson kelson   377355828 Mar  7 23:14 PostLinks.xml
-rw-r--r-- 1 kelson kelson 44071695285 Mar  7 23:14 Posts.xml
-rw-r--r-- 1 kelson kelson     3924458 Mar  7 23:14 Tags.xml
-rw-r--r-- 1 kelson kelson  1552291532 Mar  7 23:15 Users.xml
-rw-r--r-- 1 kelson kelson  9658336812 Mar  7 23:22 Votes.xml
(venv)kelson@zimfarm:/srv/sotoki$ python sotoki.py run
Traceback (most recent call last):
  File "sotoki.py", line 584, in <module>
    load(dump, database)
  File "sotoki.py", line 236, in load
    Base.metadata.create_all(session.bind)
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3687, in create_all
    tables=tables)
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1855, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1848, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1151, in _do_get
    return self._create_connection()
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/srv/sotoki/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(venv)kelson@zimfarm:/srv/sotoki$

**Comment by amirouche** [comment]
@kelson42 you need to delete the work directory or  better move it to some other place like `mv -r work superuser` and then:

```
mkdir work/dump -p
```

Move the stackoverflow dump to the above directory and run `sotoki.py run`.

**Comment by kelson42** [comment]
OK, I ran it but it went over 10GB of memory usage, so yes there is a memory consumption problem.

**Comment by amirouche** [comment]
This is a work in progress in the wiredtiger branch cf. #35

**Comment by dattaz** [comment]
merge_xml that has been merge in master normally scale for stackoverflow, on test i made have, it's can write all post and user (without offlining image) in a limited amount of memory.
