### ISSUE TITLE
--nopic mode fails to create ZIM inside docker container

### ISSUE THREAD

**Issue by satyamtg** [openzim/sotoki#154]
When in nopic mode and trying to create a ZIM inside docker container, we get the following -
```
Creating ZIM files
	Writing ZIM for Blender Stack Exchange
Traceback (most recent call last):
  File "/usr/local/bin/sotoki", line 11, in <module>
    load_entry_point('sotoki==1.3', 'console_scripts', 'sotoki')()
  File "/usr/local/lib/python3.8/site-packages/sotoki-1.3-py3.8.egg/sotoki/sotoki.py", line 1703, in run
    done = create_zims(
  File "/usr/local/lib/python3.8/site-packages/sotoki-1.3-py3.8.egg/sotoki/sotoki.py", line 1344, in create_zims
    return create_zim(
  File "/usr/local/lib/python3.8/site-packages/sotoki-1.3-py3.8.egg/sotoki/sotoki.py", line 1397, in create_zim
    os.rename(
OSError: [Errno 18] Invalid cross-device link: 'work/blender_stackexchange_com/output/static/images' -> '/tmp/tmpxax8ddk4/images'
```
This is due to the face that os.rename is used and the directories are in different devices.

**Comment by rgaudin** [comment]
Right, we shall use `shutil.move` there.

**Comment by satyamtg** [comment]
Yup. That's true. But do we really need this? (Unless we want to continue on files downloaded in a previous run).

**Comment by rgaudin** [comment]
There's no context here. What does it do? Why ? Why should it be unnecessary?

**Comment by satyamtg** [comment]
No. It's not unnecessary. I just wanted to point out that we always run on fresh scrapes, not on previously scraped data. But yup it's a small useful feature anyways.
