### ISSUE TITLE
python errors in docker container

### ISSUE THREAD

**Issue by lizfrank** [openzim/sotoki#231]
Environment:
   OS:  RHEL 7 x86.64
  
#docker run -v /tmp:/output openzim/sotoki sotoki --version
sotoki 1.3.1

Docker version 1.13.1, build 7d71120/1.13.1

Problem description:

Start the docker container: 

docker run -d -v /zimfiles:/output openzim/sotoki sotoki security.stackexchange.com Kiwix --threads=2 --reset --clean-previous --no-userprofile

"docker ps" shows the container running for about 10 minutes
 "docker logs" on the container produces the following output:

starting sotoki scraper...using /dev/shm
No cache credentials provided. Continuing without optimization cache
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/usr/local/lib/python3.8/http/client.py", line 917, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/sotoki", line 11, in <module>
    load_entry_point('sotoki==1.3.1', 'console_scripts', 'sotoki')()
  File "/usr/local/lib/python3.8/site-packages/sotoki-1.3.1-py3.8.egg/sotoki/sotoki.py", line 1585, in run
    title, description, lang_input = grab_title_description_favicon_lang(
  File "/usr/local/lib/python3.8/site-packages/sotoki-1.3.1-py3.8.egg/sotoki/sotoki.py", line 1054, in grab_title_description_favicon_lang
    get_data = urlopen(url)
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

I expect this container to run for several hours and create a file or files in the output directory.

I am running through a proxy and have the correct environment variables set, other apps are using them,  Is it possible the container python is not picking up these settings and if so, is there a way to fix that?

**Comment by rgaudin** [comment]
Hi @lizfrank, sorry about that. This version is somewhat obsolete now and won't be fixed.

As you're using docker, I suggest you try the `:dev` version. Should work fine on any domain. If you want to try it with stackoverflow, be aware that we are still actively working on some RAM consumption issues so I suggest you test it with other domains first.
