### ISSUE TITLE
Unable to scrape Mathoverflow

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#254]
[IMG-T-21::2022-05-12 16:02:32,615] DEBUG:Attempting download of S3::https/lh3.googleusercontent.com/a/AATXAJzd8iFsWekUWJ97zOTIoJz0pgVMZ28qbZnS2fAK=s96-c?sz=128 into ZIM::users/profiles/478225.webp
[MainThread::2022-05-12 16:02:35,170] DEBUG:all threads joined for T-
[MainThread::2022-05-12 16:02:35,171] DEBUG:UserGenerator Workers collected.
[MainThread::2022-05-12 16:02:37,264] DEBUG:Cleaning-up users list
[MainThread::2022-05-12 16:02:37,279] INFO:Generating Questions pages
[MainThread::2022-05-12 16:02:37,279] INFO:PROGRESS: 19.6% – Step 5/7: Questions -- 0/133364 -- Images: 15805
[MainThread::2022-05-12 16:02:37,281] ERROR:Interrupting process due to error: comments
[MainThread::2022-05-12 16:02:37,281] ERROR:comments
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.0.0-py3.8.egg/sotoki/scraper.py", line 237, in start
    self.process_questions()
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.0.0-py3.8.egg/sotoki/scraper.py", line 336, in process_questions
    PostGenerator().run()
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.0.0-py3.8.egg/sotoki/utils/generator.py", line 27, in run
    parser.parse(self.fpath)
  File "/usr/local/lib/python3.8/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/lib/python3.8/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/local/lib/python3.8/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/src/python/Modules/pyexpat.c", line 459, in EndElement
  File "/usr/local/lib/python3.8/xml/sax/expatreader.py", line 336, in end_element
    self._cont_handler.endElement(name)
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.0.0-py3.8.egg/sotoki/posts.py", line 220, in endElement
    del self.comments
AttributeError: comments
[MainThread::2022-05-12 16:02:37,358] DEBUG:shutting down executor T- with wait=False
[MainThread::2022-05-12 16:02:37,358] DEBUG:shutting down executor IMG-T- with wait=False
[MainThread::2022-05-12 16:02:37,358] INFO:PROGRESS: 19.6% – Step 5/7: Questions -- 0/133364 -- Images: 15805
[MainThread::2022-05-12 16:02:37,362] DEBUG:Removing /mathoverflow.net_ngr8blzz

From https://farm.openzim.org/pipeline/ac1e91039e86ed7e3a82d726/debug

**Comment by rgaudin** [comment]
Fogot to mark this fixed (c5b78c354136df476eb6dbec3eb925bf7afdd29e)
