### ISSUE TITLE
Unable to scrape monero.stackexchange.com

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#256]
See https://farm.openzim.org/pipeline/336e91e258211b4cbd7fc726/debug
```
[MainThread::2022-05-12 12:10:49,039] ERROR:FAILED. An error occurred: Unable to complete download and extraction
[MainThread::2022-05-12 12:10:49,039] ERROR:Unable to complete download and extraction
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.0.0-py3.8.egg/sotoki/entrypoint.py", line 344, in main
    sys.exit(scraper.run())
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.0.0-py3.8.egg/sotoki/scraper.py", line 181, in run
    ark_manager.check_and_prepare_dumps()
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.0.0-py3.8.egg/sotoki/archives.py", line 149, in check_and_prepare_dumps
    self.download_and_extract_archives()
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.0.0-py3.8.egg/sotoki/archives.py", line 124, in download_and_extract_archives
    raise Exception("Unable to complete download and extraction")
Exception: Unable to complete download and extraction
[MainThread::2022-05-12 12:10:49,042] DEBUG:Removing /monero.stackexchange.com_cgcdvedf
```

Might that be the data dump is not available (anymore)?

**Comment by kelson42** [comment]
Same for https://farm.openzim.org/pipeline/8ab5c1784190c11681684826

**Comment by kelson42** [comment]
Same for https://farm.openzim.org/pipeline/72f102ebc98ea2bc48584826

**Comment by rgaudin** [comment]
`monero` and `reverseengineering` dumps **are not available [upstream](https://archive.org/download/stackexchange) anymore**.

Both are still listed on the [Sites.xml](https://ia800107.us.archive.org/27/items/stackexchange/Sites.xml) file so it might be an error on Stack Exchange side for this March 2022 upload… Any idea how to report this upstream?

You should disable both recipes in the mean time.

PS: I checked, only those 2 are missing
