### ISSUE TITLE
No site details found for domain

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#318]
https://farm.openzim.org/pipeline/9a42bb2f-0b19-493b-91ba-63647224e7bd/debug for https://farm.openzim.org/recipes/alcohol.stackexchange.com_en

```
Starting redis.. PID: 9
[MainThread::2024-05-18 09:27:05,225] INFO:testing S3 Optimization Cache credentials
[MainThread::2024-05-18 09:27:07,060] INFO:Starting scraper with:
  domain: alcohol.stackexchange.com
  lang: ['en'] (['eng'])
  build_dir: /alcohol.stackexchange.com_dyzo8iwi
  output_dir: /output
  using cache: s3.us-west-1.wasabisys.com with bucket: org-kiwix-sotoki
[MainThread::2024-05-18 09:27:07,060] DEBUG:Fetching site details…
[MainThread::2024-05-18 09:27:08,672] ERROR:FAILED. An error occurred: "No site details found for domain='alcohol.stackexchange.com'"
[MainThread::2024-05-18 09:27:08,672] ERROR:"No site details found for domain='alcohol.stackexchange.com'"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.1.2-py3.8.egg/sotoki/entrypoint.py", line 348, in main
    sys.exit(scraper.run())
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.1.2-py3.8.egg/sotoki/scraper.py", line 152, in run
    Global.init(get_site(self.domain))
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.1.2-py3.8.egg/sotoki/utils/sites.py", line 68, in get_site
    raise KeyError(f"No site details found for {domain=}")
KeyError: "No site details found for domain='alcohol.stackexchange.com'"
[MainThread::2024-05-18 09:27:08,674] DEBUG:Removing /alcohol.stackexchange.com_dyzo8iwi

```

**Comment by benoit74** [comment]
This is a recipe configuration issue.

Technically speaking the domain name to use is still beer.stackexchange.com even if it has been moved to alcohol.stackexchange.com on the web. Dump is still made in beer.stackexchange.com and there is no dump for alcohol.stackexchange.com

@RavanJAltaie @Popolechien do you confirm you still want to create new ZIMs with the new domain name i.e. alcohol.stackexchange.com? It seems quite ok for me, it just means we must not forget to delete old ZIM which is currently named beer.stackexchange.com_xxx since it won't be automatically superseeded by the new ZIMs since name has changed

Moving this to zim-requests since scraper has no problem in this specific case
