### ISSUE TITLE
Unable to create ZIM for arabic.stackexchange.com

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#59]
```
$ sotoki arabic.stackexchange.com Kiwix
found
--2017-06-05 09:57:39--  https://archive.org/download/stackexchange/arabic.stackexchange.com.7z
Resolving archive.org (archive.org)... 207.241.224.2
Connecting to archive.org (archive.org)|207.241.224.2|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://ia800500.us.archive.org/22/items/stackexchange/arabic.stackexchange.com.7z [following]
--2017-06-05 09:57:40--  https://ia800500.us.archive.org/22/items/stackexchange/arabic.stackexchange.com.7z
Resolving ia800500.us.archive.org (ia800500.us.archive.org)... 207.241.230.50
Connecting to ia800500.us.archive.org (ia800500.us.archive.org)|207.241.230.50|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 334557 (327K) [application/x-7z-compressed]
Saving to: ‘arabic.stackexchange.com.7z’

arabic.stackexchange.com.7z                        100%[================================================================================================================>] 326.72K   675KB/s    in 0.5s    

2017-06-05 09:57:42 (675 KB/s) - ‘arabic.stackexchange.com.7z’ saved [334557/334557]

arabic.stackexchange.com.7z: OK
Ok we have get dump

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,8 CPUs)

Processing archive: arabic.stackexchange.com.7z

Extracting  Badges.xml
Extracting  Comments.xml
Extracting  PostHistory.xml
Extracting  PostLinks.xml
Extracting  Posts.xml
Extracting  Tags.xml
Extracting  Users.xml
Extracting  Votes.xml

Everything is Ok

Files: 8
Size:       1999767
Compressed: 334557
Traceback (most recent call last):
  File "/usr/local/bin/sotoki", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/sotoki/sotoki.py", line 989, in run
    title, description, lang_input = grab_title_description_favicon_lang(url, output)
  File "/usr/local/lib/python2.7/dist-packages/sotoki/sotoki.py", line 688, in grab_title_description_favicon_lang
    title = soup.find('meta', attrs={"name": u"twitter:title"})['content']
TypeError: 'NoneType' object has no attribute '__getitem__'
kelson@camber:/media/kelson/SOTOKI/work$ rm -rf arabic_stackexchange_com/
kelson@camber:/media/kelson/SOTOKI/work$ sotoki arabic.stackexchange.com Kiwix
Traceback (most recent call last):
  File "/usr/local/bin/sotoki", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/sotoki/sotoki.py", line 989, in run
    title, description, lang_input = grab_title_description_favicon_lang(url, output)
  File "/usr/local/lib/python2.7/dist-packages/sotoki/sotoki.py", line 688, in grab_title_description_favicon_lang
    title = soup.find('meta', attrs={"name": u"twitter:title"})['content']
TypeError: 'NoneType' object has no attribute '__getitem__'

```

**Comment by dattaz** [comment]
arabic.stackexchange.com is a close stackexchange forum, we agree with, at hackthon, to not take them in account.
But still IMO, we should make them one time (by hand)... (by removing from code 2-3 things that can't be download automatically)

**Comment by kelson42** [comment]
* Pourquoi le script meurt alors que visiblement tout semble oK?
* Comment je fais pour le lancer manuellement?

**Comment by dattaz** [comment]
Currently only this site (present in archive.org) is a close site.
Now there is a dict hard-code of old site we support. (we just have to find a archive version of the site in the wayback machine)

We can also ignore old site by passing `--IgnoreOldSite` as argument
