### ISSUE TITLE
Crash with moderators.meta.stackexchange.com

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#80]
```
$ sotoki moderators.meta.stackexchange.com Kiwix --threads=12 --reset --clean-previous --no-userprofile
Traceback (most recent call last):
  File "/media/kelson/SOTOKI/sotoki/venv/bin/sotoki", line 11, in <module>
    sys.exit(run())
  File "/media/kelson/SOTOKI/sotoki/venv/local/lib/python2.7/site-packages/sotoki/sotoki.py", line 1058, in run
    title, description, lang_input = grab_title_description_favicon_lang(url, output, not arguments["--ignoreoldsite"])
  File "/media/kelson/SOTOKI/sotoki/venv/local/lib/python2.7/site-packages/sotoki/sotoki.py", line 749, in grab_title_description_favicon_lang
    get_data = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

I suspect this is because this is an old site, but still it should not crash. Do we support at all old sites>

**Comment by dattaz** [comment]
This site does not exist so it is OK. It's seem this stackexchange site has been rename to communitybuilding.meta.stackexchange.com without redirection (based on the fact that moderators.stackexchange.com redirect to communitybuilding.stackexchange.com). Dump still have older name (moderators.[...]).

Also why we do meta website ? ([What's meta](https://meta.stackexchange.com/help/whats-meta))

**Comment by kelson42** [comment]
@dattaz Might that be possible to build a special handling specifically to that web site?

**Comment by dattaz** [comment]
For meta web site ?
Something like `bash list_all.sh | grep -v "meta.stackexchange.com"` ? I update list_all.sh to not like meta website ?

**Comment by kelson42** [comment]
@dattaz It is not a problem with all "meta" web site, only with this one AFAIK. So I think if someone run sotoki with `moderators.meta.stackexchange.com`, then it run `communitybuilding.meta.stackexchange.com`. And this is special handling only for that web site.

**Comment by dattaz** [comment]
Done.
We should check at next release of stackexchange dump if name of the dump is update to communitybuilding.
