### ISSUE TITLE
Crash wit productivity.meta.stackexchange.com

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#81]
```
$ sotoki productiviy.meta.stackexchange.com Kiwix --threads=12 --reset --clean-previous --no-userprofile
Traceback (most recent call last):
  File "/media/kelson/SOTOKI/sotoki/venv/bin/sotoki", line 11, in <module>
    sys.exit(run())
  File "/media/kelson/SOTOKI/sotoki/venv/local/lib/python2.7/site-packages/sotoki/sotoki.py", line 1058, in run
    title, description, lang_input = grab_title_description_favicon_lang(url, output, not arguments["--ignoreoldsite"])
  File "/media/kelson/SOTOKI/sotoki/venv/local/lib/python2.7/site-packages/sotoki/sotoki.py", line 749, in grab_title_description_favicon_lang
    get_data = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

Same as #80?

**Comment by kelson42** [comment]
Same for  productiviy.stackexchange.com

**Comment by kelson42** [comment]
Same problem with arabic.meta.stackexchange.com and arabic.stackexchange.com

**Comment by dattaz** [comment]
Same as #80 , I will think about a way to automatically deal with this situation...
I think they also change something because `arabic.stackexchange.com` should have been catch correctly...

**Comment by kelson42** [comment]
Closed forum
