### ISSUE TITLE
Impossible to scrape portuguese.stackexchange.com

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#93]
```
sotoki portuguese.stackexchange.com Kiwix --threads=3
```

dies and give:
```
  writing 256-color image as e84fd8b5e20026f4a4fa9a7c72868d9c2afff172709e30922b1edc92d960d5fe.png
Quantized 1 image.
work/portuguese_stackexchange_com/output/static/images/15b0c2b3df21a98517a650d82c3e78d1227267e97c2416d4506c8cf45a062fd6.png:
  read 8KB file
  made histogram...1700 colors found
  selecting colors...3%
  selecting colors...6%
  selecting colors...27%
  selecting colors...48%
  selecting colors...68%
  selecting colors...89%
  selecting colors...100%
  moving colormap towards local minimum
  eliminated opaque tRNS-chunk entries...0 entries transparent
  mapped image to new colors...MSE=0.646 (Q=97)
  writing 256-color image as 15b0c2b3df21a98517a650d82c3e78d1227267e97c2416d4506c8cf45a062fd6.png
  copied 1KB of additional PNG metadata
Quantized 1 image.
work/portuguese_stackexchange_com/output/static/images/dca4a4e1ff62ca39ba33942731327e998730f18ddca99abb522008cc13f559b9.png:
  read 20KB file
  made histogram...4830 colors found
  selecting colors...3%
  selecting colors...6%
  selecting colors...27%
  selecting colors...48%
  selecting colors...68%
  selecting colors...89%
  selecting colors...100%
  moving colormap towards local minimum
  eliminated opaque tRNS-chunk entries...0 entries transparent
  mapped image to new colors...MSE=1.858 (Q=93)
  writing 256-color image as dca4a4e1ff62ca39ba33942731327e998730f18ddca99abb522008cc13f559b9.png
  copied 1KB of additional PNG metadata
Quantized 1 image.
work/portuguese_stackexchange_com/output/static/images/33010d9a36811d9c8ae51a6a6048a06031436e04187e427f39cf7bcc21a2d426.png:
  read 12KB file
  made histogram...2232 colors found
  selecting colors...3%
  selecting colors...6%
  selecting colors...27%
  selecting colors...48%
  selecting colors...68%
  selecting colors...89%
  selecting colors...100%
  moving colormap towards local minimum
  eliminated opaque tRNS-chunk entries...0 entries transparent
  mapped image to new colors...MSE=0.642 (Q=97)
  writing 256-color image as 33010d9a36811d9c8ae51a6a6048a06031436e04187e427f39cf7bcc21a2d426.png
  copied 1KB of additional PNG metadata
Quantized 1 image.
work/portuguese_stackexchange_com/output/static/images/134bf83ecc16fd34b41e4958183572c0ac498cba4feeb673dba9b424899a9c7c.png:
  read 40KB file
  made histogram...6040 colors found
  selecting colors...3%
  selecting colors...6%
  selecting colors...27%
  selecting colors...48%
  selecting colors...51%
  selecting colors...55%
  selecting colors...75%
  selecting colors...79%
  selecting colors...82%
  selecting colors...100%
  moving colormap towards local minimum
  eliminated opaque tRNS-chunk entries...0 entries transparent
  mapped image to new colors...MSE=0.876 (Q=97)
  writing 256-color image as 134bf83ecc16fd34b41e4958183572c0ac498cba4feeb673dba9b424899a9c7c.png
  copied 1KB of additional PNG metadata
Quantized 1 image.
Traceback (most recent call last):
  File "/usr/local/bin/sotoki", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/sotoki/sotoki.py", line 1111, in run
    parser.parse(os.path.join(dump, "Tags.xml"))
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 336, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/usr/local/lib/python2.7/dist-packages/sotoki/sotoki.py", line 332, in startElement
    print(attrs["TagName"])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 7: ordinal not in range(128)
```

See https://farm.openzim.org/pipeline/5e10dc76befd34b6532bfcf2/debug

**Comment by kelson42** [comment]
@dattaz Would you be able to help on this one? We are setuping currently the whole periodic and automatic SE scraping with Sotoki in the Zimfarm.

**Comment by amirouche** [comment]
It is probably better to try to fix after the move the Python 3 (https://github.com/openzim/sotoki/issues/92) because Python 3 provides some enhancement regarding unicode.

Also I am wondering why `ascii` codec is in the mix, it should not happen, since IIRC stackexchange dump is utf-8.

**Comment by kelson42** [comment]
This happens on ~ 3-4 SE sites, all of them related to non-english languages. So, I guess the charset mgmt is wrong somewhere.

**Comment by dattaz** [comment]
> @dattaz Would you be able to help on this one? We are setuping currently the whole periodic and automatic SE scraping with Sotoki in the Zimfarm.

No before 2 weeks sorry :/

**Comment by kelson42** [comment]
@dattaz If you could do this migration in 2 weeks, that would be already great!

**Comment by kelson42** [comment]
Fixed with https://github.com/openzim/sotoki/commit/acb279f523e00e31679cbd28e6866fa74e278bfc
